/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleJava;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
public static void main (String[] args)
    App hitung = new App();
    System.out.println(hitung.kali)(2,3));
    System.out.println(hitung.bagi)(2,3));
    System.out.println(hitung.tambah)(2,3));
    System.out.println(hitung.kurang)(2,3));
    
}